#!/usr/bin/env bash
#
# Summary:
#    Update all outdated packages
#
# Usage: pm-apt update
#

echo "** Apt **"
if [ -z "$(command -v sudo)" ]; then
  apt-get update -y && \
  apt-get upgrade -y
else
  sudo apt-get update -y && \
  sudo apt-get upgrade -y
fi

